name: flex_ride
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  fluttertoast: ^8.2.4
  google_maps_flutter: ^2.6.0
  geolocator: ^11.0.0
  http: ^1.2.1
  provider: ^6.1.2
  location: ^5.0.3
  permission_handler: ^11.3.1
  flutter_dotenv: ^5.1.0
  flutter_polyline_points: ^2.0.0
  file_picker: ^5.5.0
  firebase_storage: ^11.7.0
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - images/car_android0.png
    - images/car_ios0.png
    - images/desticon0.png
    - images/desticon1.png
    - images/logo.png
    - images/logo1.png
    - images/pickicon.png
    - images/posimarker.png
    - images/redmarker.png
    - images/taxi.png
    - images/user_icon.png
    - .env

  fonts:
    - family: Signatra
      fonts:
        - asset: fonts/Signatra.ttf
    - family: Brand-Regular
      fonts:
        - asset: fonts/bolt-regular.ttf
    - family: Brand Bold
      fonts:
        - asset: fonts/bolt-semibold.ttf
